# Generated by Django 4.1 on 2023-11-22 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_zone', models.IntegerField(verbose_name='id области')),
                ('in_zone', models.IntegerField(verbose_name='вошло в область')),
                ('out_zone', models.IntegerField(verbose_name='вышло из области')),
            ],
        ),
    ]
